jenkins:
  systemMessage: "\n\nMagento 2 Docker Images Jenkins setup\n\n"
  mode: NORMAL
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: ${ADMIN_PASSWORD}

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "git-token"
              username: ${GIT_USERNAME}
              password: ${GIT_PERSONAL_ACCESS_TOKEN}
              description: "Git personal access token (PAT)"

jobs:
  - script: >
      pipelineJob('Magento Docker Images') {
          definition {
              cpsScm {
                  scm {
                      git {
                          remote {
                              url('${GIT_REPOSITORY}')
                              credentials('git-token')
                          }
                          branch('${PIPELINE_BRANCH}')
                      }
                  } 
                  
                  lightweight()
              }
          }
          environmentVariables {
              envs(
                REGISTRY_CONFIG_OVERWRITE: '${REGISTRY_CONFIG_OVERWRITE}'
              )
          }
      }
